# Generated by Django 2.1.2 on 2018-12-22 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0002_auto_20181221_2115'),
        ('posts', '0004_auto_20181222_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='post',
            name='voters',
            field=models.ManyToManyField(related_name='voted_posts', through='votes.PostVote', to=settings.AUTH_USER_MODEL),
        ),
    ]
