# Generated by Django 2.1.5 on 2019-02-03 18:22

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190129_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_bleach.models.BleachField(),
        ),
    ]
