# Generated by Django 2.1.2 on 2018-10-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
