# Generated by Django 2.1.2 on 2018-10-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0002_sub_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub',
            old_name='admins',
            new_name='moderators',
        ),
    ]
