# Generated by Django 2.1.2 on 2018-10-08 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subs', '0003_auto_20181008_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sub',
            name='moderators',
            field=models.ManyToManyField(related_name='moderated_sub', to=settings.AUTH_USER_MODEL),
        ),
    ]
