# Generated by Django 2.1.2 on 2018-10-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0005_auto_20181010_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
