# Generated by Django 2.1.2 on 2019-01-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0006_auto_20181011_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='sub',
            name='title',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
