# Generated by Django 2.1.2 on 2018-12-14 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0005_auto_20181214_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.IntegerField(choices=[(1, 'upvote'), (-1, 'downvote'), (0, 'no_vote')], default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='commentvotes',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='commentvotes',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentvotes',
            name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='voters',
            field=models.ManyToManyField(related_name='voted_comments', through='comments.CommentVote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CommentVotes',
        ),
        migrations.AddField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='comments.Comment'),
        ),
        migrations.AddField(
            model_name='commentvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together={('comment', 'user')},
        ),
    ]
