# Generated by Django 2.1.2 on 2018-12-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20181214_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
    ]
