# Generated by Django 2.1.2 on 2018-12-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_remove_comment_upvotes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='voters',
        ),
        migrations.DeleteModel(
            name='CommentVote',
        ),
    ]
