# Generated by Django 2.1.5 on 2019-02-03 18:45

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20190131_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=django_bleach.models.BleachField(),
        ),
    ]
