# Generated by Django 2.1.2 on 2018-10-10 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0005_auto_20181010_1527'),
        ('redditors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subs.Sub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subs',
            field=models.ManyToManyField(related_name='members', through='redditors.UserSubMembership', to='subs.Sub'),
        ),
    ]
