# Generated by Django 2.1.2 on 2018-10-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditors', '0002_auto_20181010_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmembership',
            name='sign_up_date',
            field=models.DateTimeField(auto_now_add=True, blank=True),
            preserve_default=False,
        ),
    ]
