# Generated by Django 2.1.2 on 2018-11-13 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0006_auto_20181011_2214'),
        ('redditors', '0003_usersubmembership_sign_up_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersubmembership',
            unique_together={('user', 'sub')},
        ),
    ]
